runtime: nodejs14

handlers:
  - url: /(.*\.(css|js|map|json|ico|png|jpg|jpeg|gif|woff|woff2|ttf|svg))
    static_files: build/\1
    upload: build/.*\.(css|js|map|json|ico|png|jpg|jpeg|gif|woff|woff2|ttf|svg)
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
